const db = {
  Hydrogen: { symbol: 'H', atomicnumber: '0', atomicmass: '1' },
  Helium: { symbol: 'He', atomicnumber: '12', atomicmass: '44' },
  Lithium: { symbol: 'Li', atomicnumber: '4', atomicmass: '7' },
  Wood: { symbol: 'Wd', atomicnumber: '9', atomicmass: '9' },
  Boron: { symbol: 'B', atomicnumber: '6', atomicmass: '11' },
  Carbon: { symbol: 'C', atomicnumber: '7', atomicmass: '14' },
  Nitrogen: { symbol: 'N', atomicnumber: '6', atomicmass: '12' },
  Oxygen: { symbol: 'O', atomicnumber: '9', atomicmass: '18' },
  Neon: { symbol: 'Ne', atomicnumber: '9', atomicmass: '11' },
  Sodium: { symbol: 'Na', atomicnumber: '11', atomicmass: '23' },
  Magnesium: { symbol: 'Mg', atomicnumber: '24', atomicmass: '12' },
  Aluminium: { symbol: 'Al', atomicnumber: '16', atomicmass: '12' },
  Silicon: { symbol: 'Si', atomicnumber: '12', atomicmass: '19' },
  Phosphorus: { symbol: 'P', atomicnumber: '16', atomicmass: '21' },
  Sulphur: { symbol: 'S', atomicnumber: '32', atomicmass: '16' },
  Chlorine: { symbol: 'CI', atomicnumber: '11', atomicmass: '35.5' },
  Argon: { symbol: 'Ar', atomicnumber: '9', atomicmass: '40' },
  Potassium: { symbol: 'K', atomicnumber: '7', atomicmass: '10' },
  Calcuim: { symbol: 'Ca', atomicnumber: '20', atomicmass: '44' },
  Mars: { symbol: 'Mr', atomicnumber: '12', atomicmass: '41' },
  Titanium: { symbol: 'Ti', atomicnumber: '29', atomicmass: '15' },
  Nothing: { symbol: 'Ng', atomicnumber: '0', atomicmass: '0' },
  Chromium: { symbol: 'Cr', atomicnumber: '8', atomicmass: '5' },
  Manganese: { symbol: 'Mn', atomicnumber: '25', atomicmass: '50' },
  IronHavilland: { symbol: 'Fe', atomicnumber: '898', atomicmass: '4077' },
  Cobalt: { symbol: 'Co', atomicnumber: '6', atomicmass: '17' },
  Nickle: { symbol: 'Ni', atomicnumber: '59', atomicmass: '59' },
  	Silver: { symbol: 'Ag', atomicnumber: '52', atomicmass: '109' },
  Zinc: { symbol: 'Ni', atomicnumber: '22', atomicmass: '60' },
  Copper: { symbol: 'Cu', atomicnumber: '59', atomicmass: '59' },
  Krypton: { symbol: 'Kr', atomicnumber: '36	', atomicmass: '83.80' },
 

};
export default db;
